### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/hr-attendance#73]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [x] hr_attendance_autoclose - By @aleuffre - #116
- [x] hr_attendance_geolocation - By @extrememicro - #95
- [x] hr_attendance_modification_tracking - By @dalonsofl - #145
- [x] hr_attendance_reason - By @victoralmau - #146
- [x] hr_attendance_report_theoretical_time - By @dzungtran89 - #121
- [x] hr_attendance_rfid - By @victoralmau - #157
- [x] hr_birthday_welcome_message - By @luisDIXMIT - #169

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by dsolanki-initos** [comment]
hr_attendance_reason https://github.com/OCA/hr-attendance/pull/112

**Comment by dzungtran89** [comment]
- hr_attendance_report_theoretical_time:https://github.com/OCA/hr-attendance/pull/121

**Comment by dalonsofl** [comment]
- hr_attendance_modification_tracking : https://github.com/OCA/hr-attendance/pull/145#top

**Comment by etobella** [comment]
I close the issue, as everything is solved :tada:
